### PR TITLE
Footstep effect v2

### PR DESCRIPTION
**Pull request by piptouque**
### What :

Footstep effect added on camera movement

### How to test :

Move around using z, q, s, d keys
Orbite camera using the mouse

I especially need you to tell me if the movement corresponds to an old fisherman ? It may be easier to see it in a less empty environment.

### CODE REVIEW

**Comment by piptouque** [comment]
I can attest that the changes work for me. As for the movement matching an old fisherman's, I like that it's wobbly, but it might be tad too much. Is there a way to control the 'strength' of the step animation?

**Review by MonicaLis — APPROVED** [review]
It works perfectly well for me too, but I agree with Pierre, it's slightly too wobbly! I'll be adding the 3D environment in a sec so it'll give us a better idea of how wobbly we want our old man to be :-)

**Review by lrathoni — CHANGES_REQUESTED** [review]
Good job, it works well ! Like Pierre and Monica, I think the character's movement is a little exagerated (especially on the extrem left and right sides of the camera)

**Review by roxyvallee — APPROVED** [review]
The keys Z Q S D work, also the camera is moving depending of the mouse.
Like the others, I think the movement is a little too abrupt, it makes you dizzy.
Maybe it can be softer.

**Pull request closed without merging**
