### PR TITLE
3D environment

### PR DESCRIPTION
**Pull request by MonicaLis**
Just to check that everyone can see the 3D environment for the hub scene.

### CODE REVIEW

**Review by roxyvallee — APPROVED** [review]
I can see the different 3D objects of the scene with their textures.

**Review by lrathoni — APPROVED** [review]
Good for me

**Comment by piptouque** [comment]
Bit of a nitpick here, but I can't the interior of the bucket (backface culling, probably).
edit: I meant that the inside of the bucket is not rendered due to it being the back of the mesh.

**Review by piptouque — APPROVED** [review]

**Comment by Lchikar** [comment]
Ok for me 👌

**Review by Lchikar — APPROVED** [review]

**Pull request merged**
