### PR TITLE
[Add]: Hub scene with character and camera controllers

### PR DESCRIPTION
**Pull request by Lchikar**
**What :** 
- First camera control
- First character control

**How to test :**
- Checkout on branch char_cam_ctrl
- Launch Hub scene on play mode
- Move character using z, q, s, d keys
- Move camera using the mouse

### CODE REVIEW

**Review by MonicaLis — COMMENTED** [review]
Everything works on my side :)

**Review by lrathoni — APPROVED** [review]
All is right

**Review by piptouque — APPROVED** [review]
Good stuff

**Review by roxyvallee — APPROVED** [review]
All functionality works

**Pull request merged**
